version: 1
services:
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
        - "80:80"
    volumes:
        - web-root:/var/www/html
        - ./nginx-conf:/etc/nginx/conf.d

    depends_on:
        - backend
    networks:
        - backend_net
  
  mongodb:
    image: mongo:4.4
    restart: unless-stopped
    ports:
        - 27017:27017
    volumes:
        - ~/apps/mongo:/data/db
    environment:
        - MONGO_INITDB_ROOT_USERNAME=mongoroot
        - MONGO_INITDB_ROOT_PASSWORD=pa$$w
    networks:
        -backend_net

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    restart: unless-stopped
    cpus: 2
    mem_limit: 4000
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - backend_net

  redis:
    image: "redis:alpine"
    networks:
      - backend_net

networks:
  backend_net: