version: '3.1'
services:
  mongodb:
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - 27017
    volumes:
      - db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoroot
      - MONGO_INITDB_ROOT_PASSWORD=pass135
      - MONGO_INITDB_ROOT_DATABASE=database

  backend:
    container_name: crud
    build:
      context: .
      dockerfile: Dockerfile
    image: crud
    restart: unless-stopped
    environment:
      - DB_HOST=mongodb
      - DB_USER=mongoroot
      - DB_PASSWORD=pass135
      - DB_NAME=database
      - DB_PORT=27017
      - PORT=4000
    ports:
      - 4000
    depends_on:
      - mongodb

  nginx:
    build:
      context: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db:
networks:
  default:
    name: priv-net